#!/bin/bash

sudo apt-get update
git clone https://github.com/adrelanos/nothing-to-see
git -C "/home/user/nothing-to-see"
git tag
git -C "/home/user/nothing-to-see" checkout 7.7.3.5
sudo ./nothing-to-see/whonix_build --tor-gateway --bare-metal --build >> /home/user/log7735 2>> /home/user/log7735
